name: TreeFeller
version: 1.0
author: Thomas Herbert
main: me.Herbert.Thomas.MinecraftPlugins.TreeFeller.Main.Main
description: Destroys entire trees when you break the bottom block of it
api-version: 1.16